In [1]:
import openl3
import soundfile as sf

import sound_utils

import numpy as np

from matplotlib import pyplot as plt
import librosa.display

import IPython.display as ipd

import keras
from keras.layers import Input
from keras.models import Model
import kapre
from kapre.time_frequency import Melspectrogram

%matplotlib inline

Using TensorFlow backend.
/home/prs392/miniconda3/envs/incubator/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/prs392/miniconda3/envs/incubator/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/prs392/miniconda3/envs/incubator/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pr

In [37]:
audio, sr = sf.read('/scratch/prs392/incubator/data/LibriSpeech/train_clean_360/LibriSpeech/train-clean-360/100/121669/100-121669-0015.flac')

audio.shape, sr

((254800,), 16000)

In [38]:
emb, ts = openl3.get_audio_embedding(audio, sr, center=False)

emb.shape, ts.shape

151/151 [==============================] - 2s 14ms/step


((151, 6144), (151,))

In [4]:
emb

array([[ 2.8323328 ,  2.1989398 ,  2.83681   , ..., -0.35442752,
         2.144751  ,  0.64459395],
       [ 3.0416768 ,  1.8845478 ,  2.792117  , ..., -0.35006118,
         2.1530495 ,  0.6906469 ],
       [ 3.1315477 ,  1.9833739 ,  2.2977023 , ..., -0.35379124,
         2.1468534 ,  0.67706096],
       ...,
       [ 3.299561  ,  2.1290104 ,  2.8619537 , ..., -0.3439855 ,
         2.1069603 ,  0.7533889 ],
       [ 3.4373739 ,  1.9691268 ,  2.6896493 , ..., -0.3442179 ,
         2.1073806 ,  0.75327367],
       [ 3.2541075 ,  2.50879   ,  2.1347528 , ..., -0.4950045 ,
         2.3020587 ,  0.73868185]], dtype=float32)

In [44]:
audio_data_first = audio[0:0+16000]

if audio_data_first.shape[0] != 16000:

    audio_data_first = np.pad(audio_data_first,
                        ((0, 16000 - audio_data_first.shape[0]),),
                        mode='constant')

In [45]:
audio_data_first.shape

(16000,)

In [46]:
emb_1, ts_1 = openl3.get_audio_embedding(audio_data_first, sr, center=False)

type(emb_1)

1/1 [==============================] - 1s 557ms/step


numpy.ndarray

In [48]:
np.allclose(emb[0], emb_1, rtol=1e-10, atol=1e-10)

False

In [49]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [51]:
emb[0]

array([ 2.83233285e+00,  2.19893980e+00,  2.83681011e+00,  3.05041701e-01,
        2.83111811e+00,  1.12211633e+00,  1.16612720e+00,  9.52410042e-01,
        1.90862763e+00,  4.55802059e+00,  1.05675948e+00,  1.31599629e+00,
        1.41449022e+00,  2.63957787e+00,  1.01617813e+00,  9.28609312e-01,
        1.40516913e+00,  2.42412663e+00,  6.72309101e-01,  2.20807958e+00,
        2.29609656e+00,  1.93559754e+00,  1.68004990e+00,  4.84249210e+00,
        1.02920389e+00,  2.90238595e+00,  1.43153381e+00,  2.35185456e+00,
        1.26375222e+00,  2.15199709e+00,  1.87828636e+00,  9.42711532e-01,
        4.56424922e-01,  2.33454013e+00,  1.26342094e+00,  4.75214571e-01,
        1.26734710e+00,  2.43097377e+00,  2.51263309e+00,  4.74990559e+00,
        1.23819280e+00,  2.99520278e+00,  6.47167265e-01,  1.95195627e+00,
        1.46745300e+00,  2.81732231e-02,  4.62246037e+00,  1.43462431e+00,
        8.48891139e-01,  3.26062298e+00,  1.94172025e+00,  1.41021752e+00,
        7.91432381e-01,  

In [52]:
emb_1

array([[ 2.83233213e+00,  2.19893765e+00,  2.83680534e+00,
         3.05041879e-01,  2.83111954e+00,  1.12211621e+00,
         1.16612625e+00,  9.52410340e-01,  1.90862727e+00,
         4.55801821e+00,  1.05675650e+00,  1.31599629e+00,
         1.41449058e+00,  2.63957596e+00,  1.01617765e+00,
         9.28607345e-01,  1.40516782e+00,  2.42412758e+00,
         6.72308862e-01,  2.20807958e+00,  2.29609394e+00,
         1.93559659e+00,  1.68005049e+00,  4.84249306e+00,
         1.02920341e+00,  2.90238476e+00,  1.43153429e+00,
         2.35185552e+00,  1.26375246e+00,  2.15199685e+00,
         1.87828493e+00,  9.42709208e-01,  4.56424624e-01,
         2.33453870e+00,  1.26342034e+00,  4.75213796e-01,
         1.26734698e+00,  2.43097258e+00,  2.51263165e+00,
         4.74990749e+00,  1.23819304e+00,  2.99520397e+00,
         6.47165000e-01,  1.95195484e+00,  1.46745157e+00,
         2.81737261e-02,  4.62245941e+00,  1.43462241e+00,
         8.48889291e-01,  3.26062441e+00,  1.94172120e+0

In [32]:
emb_1

array([[ 3.2540998 ,  2.5087886 ,  2.1347642 , ..., -0.37264317,
         2.1958022 ,  0.7376672 ]], dtype=float32)

In [30]:
1e-1 + 1e-10 * np.abs(3.2540998)

0.10000000032540998

In [1]:
import numpy as np

In [2]:
with open('/scratch/prs392/incubator/data/LibriSpeech/train_clean_360/LibriSpeech/processed/train-clean-360/8113-117384-0020.npy', 'rb') as f:
    emb = np.load(f)
    

In [4]:
emb.shape

(6144,)